version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student-net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: students_db
    networks:
      - student-net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - student-net

volumes:
  mysql_data:

networks:
  student-net:
    driver: bridge
